# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:v0.12.0
    build: .
    command: bundle exec jekyll serve --host 0.0.0.0 --port 4000
    ports:
      - 1234:1234
      - 4000:4000
    volumes:
      - .:/srv/jekyll
    environment:
      - JEKYLL_ENV=development
